# Generated by Django 4.1.7 on 2023-04-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('logo', models.URLField()),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=0)),
                ('against_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='againstteam', to='match.team')),
                ('team_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='match.team')),
            ],
        ),
    ]
