# Generated by Django 4.1.7 on 2023-04-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_score', models.IntegerField(default=0)),
                ('against_team_score', models.IntegerField(default=0)),
                ('is_live', models.BooleanField(default=False)),
                ('live_against_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liveagainstteam', to='match.team')),
                ('live_team_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='match.team')),
            ],
        ),
    ]
