# Generated by Django 4.1.7 on 2023-04-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='ga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='gd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='gf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='gp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='w',
            field=models.IntegerField(default=0),
        ),
    ]
