# Generated by Django 4.1.7 on 2023-04-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_team_d_team_ga_team_gd_team_gf_team_gp_team_l_team_w'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Matchtop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=25)),
                ('image', models.URLField()),
            ],
        ),
    ]
